### ISSUE TITLE
Failed CloudFormation

### ISSUE THREAD

**Issue by AlbertoGarciaArdiles** [aws-quickstart/quickstart-microsoft-wapadfs#2]
Hi Guys I've tried to deploy the Existing VPC Option from this QuickStart against an AWS Directory Service

But receive this failure:

WaitCondition received failed message: 'Command failure in C:\cfn\scripts\Install-ADFS.ps1 on line 196 Exception: System.Management.Automation.RemoteException: Cannot index into a null array.' for uniqueId: i-0534d27197592ef8f

The problem occured in the line 196 of C:\cfn\scripts\Install-ADFS.ps1

As far as I've checked there the certutil is not retrieving no Certificate...

Any advice?

**Comment by davmayd** [comment]
This Quick Start requires a CA in the Active Directory domain in order to deploy. From any domain-joined server, you can run the following in an elevated PowerShell windows to create a CA:

Add-WindowsFeature Adcs-Cert-Authority -IncludeManagementTools
Install-AdcsCertificationAuthority -CAType EnterpriseRootCA
