### ISSUE TITLE
AD/ADFS/WAP Auto Scaling

### ISSUE THREAD

**Issue by cddiggs** [aws-quickstart/quickstart-microsoft-wapadfs#6]
This is more of a design question more than an Issue. If I need to post this question else where, please let me know.

I noticed Auto Scaling was added to the RDGWs, but not the AD/ADFS/WAP instances. Why?

Would it be possible to add the AD/ADFS/WAP instances to an Auto Scaling group to scale out/in instances? I figure if this was a capability that could be achieved, it would have already been implemented in these Quick Start repos. Any recommendations/comments/direction would be greatly appreciated. Thanks

**Comment by virtlima** [comment]
The way the Auto-Scaling Groups work with RDGW is to replace the node if there is a failure. It re-launches a new Instance and does some configuration, there is no concerns over stateful information in that case, minimal impact.  
 
With ADFS, you want to have a minimum of two nodes in two different AZs to ensure High Availability, and that the data is being replicated because in that case we are dealing with stateful data in our application. At the time the Quick Start was built they probably where leaning more toward a standard architecture from a Microsoft perspective for ADFS.
 
That being said, you probably can go the route of Auto-Scaling maintaining a minimum group of 2 for ADFS/WAP.  It would really come down to how you orchestrate the addition of Servers on scale-out and the removal of them in the case of scale-in and load balancing the traffic and health checks etc. You would most likely want to take a look at [EC2 Auto-Scaling LifeCycle Hooks](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html), and PowerShell DSC with [AWS Systems Manager ](https://www.youtube.com/watch?v=Z_S1bKTg1FA&t=12s)to help with the configuration portion. However, you would not want to consider an Auto-Scaling group of 1 as in RDGW, because you would lose changes or updates to ADFS.
 
Hope this helps. We do have plans on updating this Quick Start in time, we will take this feedback into consideration.

**Comment by cddiggs** [comment]
Great! Thanks for your input.
